apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: semics
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: iot-healthcheck
  name: iot-healthcheck
  namespace: semics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-healthcheck
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: iot-healthcheck
    spec:
      containers:
      - image: iot-healthcheck
        name: iot-healthcheck
        resources: {}
        env: 
        - name: ELASTIC_APM_SERVER_URL 
          value: "http://apm-server-apm-http:8200" 
        - name: ELASTIC_APM_SERVICE_NAME 
          value: "iot_healthcheck" 
        - name: ELASTIC_APM_APPLICATION_PACKAGES 
          value: "com.examples" 
        - name: ELASTIC_APM_ENVIRONMENT 
          value: test 
        - name: ELASTIC_APM_LOG_LEVEL 
          value: DEBUG 
        
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: iot-healthcheck
  name: iot-healthcheck
  namespace: semics
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: iot-healthcheck
  type: ClusterIP
status:
  loadBalancer: {}
